<?php

namespace Tests\Unit;

use App\Models\Orders;
use Tests\TestCase;

class AdminTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withoutMiddleware();
    }

    private function makeDummyRuleObject(int $id)
    {
        $order = new Orders();

        $order->user_id = $id;
        $order->phone_id = 'Samsung S21';
        $order->amount = 3;
        $order->status = 'processed';
        $order->total_price = 105;

        return $order;
    }

    /** @test */
    public function it_will_cancel_order()
    {
        $order = $this->makeDummyRuleObject(1);

        $response = $this->get('/api/v1/cancel/' . $order->id);

        $response->assertStatus(200);
    }

    /** @test */
    public function it_will_not_cancel_order_cause_it_does_not_exists()
    {
        $response = $this->get('/api/v1/cancel/5');

        $response->assertStatus(404);
    }

    /** @test */
    public function it_will_fulfill_order()
    {
        $order = $this->makeDummyRuleObject(2);

        $response = $this->get('/api/v1/fulfill/' . $order->id);

        $response->assertStatus(200);
    }

    /** @test */
    public function it_will_not_fulfill_order_cause_it_does_not_exists()
    {
        $response = $this->get('/api/v1/fulfill/7');

        $response->assertStatus(404);
    }
}
